#! /bin/sh

sxhkd &
picom &

feh --bg-fill "$(find "$HOME/.cache/dotfiles/bg" -type f | shuf | head -1)" --no-fehbg

bspc monitor -d AUDIO FF WEB IV V VI VII VIII IX X

bspc config border_width            2
bspc config window_gap             10

bspc config split_ratio            0.60
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config single_monocle         true

bspc config ignore_ewmh_fullscreen none

bspc config pointer_modifier       shift
bspc config pointer_action1        move
bspc config pointer_action2        resize_corner

bspc rule    -a '*:qjackctl'    desktop=AUDIO state=floating
bspc rule    -a '*:pavucontrol' desktop=AUDIO state=floating rectangle=750x450+2675+887
bspc rule    -a 'Firefox'       desktop=FF
bspc rule    -a 'XDaliClock'    state=floating sticky=on hidden=on rectangle=223x82+1610+300

xdaliclock -24 -noseconds -builtin1 -transparent -nocycle -fg darkgreen &
# qjackctl &
# pavucontrol &
