#! /bin/sh

source "$HOME/.profile"
xrdb "$HOME/.Xresources"

killall pulseaudio
sxhkd &
qjackctl &

bspc monitor -d I II WEB IV V VI VII VIII IX X

bspc config border_width            2
bspc config window_gap             10

bspc config split_ratio            0.60
bspc config borderless_monocle     true
bspc config gapless_monocle        true

bspc config ignore_ewmh_fullscreen all

bspc config pointer_modifier       shift
bspc config pointer_action1        move
bspc config pointer_action2        resize_corner

bspc rule -a *:qjackctl state=floating center=on
