#!/usr/bin/env sh
/usr/bin/env picom &
/usr/bin/env taffybar &
/usr/bin/env firefox -p openbox &
# wine "$HOME/.wine-3d-printing/drive_c/Program Files/Autodesk/webdeploy/production/6a0c9611291d45bb9226980209917c3d" &
