# Skip the not really helping Ubuntu global compinit
skip_global_compinit=1

if [ -f "/etc/profile" ]; then
	source "/etc/profile"
fi
if [ -d "/etc/profile.d" ]; then
	for file in /etc/profile.d/*.sh; do
		source "$file";
	done
fi

export PATH="$HOME/.local/bin:$PATH"

export EDITOR="/usr/bin/emacsclient"
export VISUAL="$EDITOR"

