#!/usr/bin/env zsh

autoload -U select-word-style
select-word-style bash

export XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"

# History configuration
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=999999999
export SAVEHIST=999999999

setopt BANG_HIST
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_VERIFY
# END History configuration

typeset -A ZINIT
ZINIT_HOME="$XDG_CACHE_HOME/dotfiles/zsh/zinit"
ZINIT[HOME_DIR]="$ZINIT_HOME"
ZINIT[ZCOMPDUMP_PATH]="$XDG_CACHE_HOME/zsh/zcompdump"

if ! [ -f "$ZINIT_HOME/zinit.zsh.zwc" ]; then
    zcompile "$ZINIT_HOME/zinit.zsh";
fi
source "$ZINIT_HOME/zinit.zsh"

zinit ice lucid nocd atload="!source $XDG_CACHE_HOME/dotfiles/zsh/p10k.zsh"
zinit load romkatv/powerlevel10k

zinit lucid wait for \
      willghatch/zsh-saneopt \
      rupa/z                 \
      mollifier/cd-gitroot   \
      micha/resty            \
      supercrabtree/k        \
      aperezdc/virtualz      \
      Aloxaf/fzf-tab

zinit ice lucid wait atload="_zsh_autosuggest_start"
zinit load zsh-users/zsh-autosuggestions

zinit lucid wait atload="zicompinit; zicdreplay" for \
      zdharma/fast-syntax-highlighting \
      zsh-users/zsh-completions \
      ninrod/pass-zsh-completion

alias l='k --no-vcs -h'
alias k='k -h'

# Define keybinds
ZKBD_FILE="$HOME/.zkbd/$TERM-${${DISPLAY:t}:-$VENDOR-$OSTYPE}"

if ! [ -f "$ZKBD_FILE" ]; then
    autoload zkbd
    zkbd
fi

if [ -f "$ZKBD_FILE" ]; then
    source "$ZKBD_FILE"
    [ -n "${key[Home]}" ]    && bindkey "${key[Home]}"    beginning-of-line
    [ -n "${key[End]}" ]     && bindkey "${key[End]}"     end-of-line
    [ -n "${key[Delete]}" ]  && bindkey "${key[Delete]}"  delete-char
fi
